version: '3'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.boardlooker.rule=Host(`boardlooker-api.timofeev41.com`)"
      - "traefik.http.routers.boardlooker.tls=true"
      - "traefik.http.routers.boardlooker.tls.certresolver=letsencrypt"

    networks:
      - proxy

networks:
  proxy:
    name: proxy
