version: '3'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`boardlooker-api.timofeev41.com`)"
    networks:
      - proxy

networks:
  proxy:
    name: proxy
