version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`api.timofeev41.com`)"
      - "traefik.http.routers.fastapi.tls=true"
      - "traefik.http.routers.fastapi.tls.certresolver=letsencrypt"

    networks:
      - proxy

networks:
  proxy:
    name: proxy